dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - npm install --global truffle
  - npm install
  - truffle version
script:
  - npm run test
